# Macro file for the initialization of example B2 
# in interactive session
#
# Set some default verbose
/control/verbose 0
#/control/saveHistory
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac

# ----- select physics list -----
#/UKAL_sim/phys/addPhysics LEND
/UKAL_sim/phys/addPhysics Standard_EM